# Dependabot dependency version checks / updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    # This will update the Cargo.lock
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      deps:
        patterns:
          - "*"
  - package-ecosystem: "cargo"
    # This will update the cargo-quickinstall/Cargo.toml
    directory: "/cargo-quickinstall"
    schedule:
      interval: "daily"
    groups:
      deps:
        patterns:
          - "*"
  - package-ecosystem: "pip"
    # This will update cronjob_scripts/requirements.txt
    directory: "/cronjob_scripts"
    schedule:
      interval: "daily"
