name: Setup env for cronjob and cache

runs:
  using: composite
  steps:
    - name: Export CARGO_TARGET_DIR
      run: cygpath -w /tmp/target | tee -a "$GITHUB_ENV"
      shell: bash
      if: runner.os == 'Windows'

    - name: Export CARGO_TARGET_DIR
      run: echo /tmp/target >> "$GITHUB_ENV"
      shell: bash
      if: runner.os != 'Windows'
        
    - uses: actions/cache@v4
      with:
        path: ${{ env.CARGO_TARGET_DIR }}
        key: ${{ runner.os }}-${{ matrix.target_arch }}-self-build-with-build-version
