[package]
name = "cargo-quickinstall stats server"
version = "0.1.0"
edition = "2021"

# Make a new workspace so that we get our own Cargo.lock and target dir for the docker build. 
[workspace]

[dependencies]
