# fly.toml file generated for holy-grass-8371 on 2021-04-06T14:31:33-04:00

app = "hello-rust"

kill_signal = "SIGINT"
kill_timeout = 5

[experimental]
# required because we can't infer your binary's name
cmd = "./hello"

[env]
PORT = "8080"

[[services]]
internal_port = 8080
protocol = "tcp"

[services.concurrency]
hard_limit = 25
soft_limit = 20

[[services.ports]]
handlers = ["http"]
port = "80"

[[services.ports]]
handlers = ["tls", "http"]
port = "443"

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
port = "8080"
restart_limit = 6
timeout = "2s"
